inputSpec: https://developer.ebay.com/api-docs/master/buy/feed/openapi/3/buy_feed_v1_beta_oas3.yaml
invokerPackage: Ebay
modelPackage: Ebay\Model\Buy\Feed
apiPackage: Ebay\Api\Buy\Feed
packageName: uapl/ebay-openapi
generatorName: php