inputSpec: https://developer.ebay.com/api-docs/master/buy/order/openapi/3/buy_order_v2_oas3.yaml
invokerPackage: Ebay
modelPackage: Ebay\Model\Buy\Order
apiPackage: Ebay\Api\Buy\Order
packageName: uapl/ebay-openapi
generatorName: php