'!include': 'common.yml'
inputSpec: https://developer.ebay.com/api-docs/master/commerce/taxonomy/openapi/3/commerce_taxonomy_v1_oas3.json
modelPackage: Model\Commerce\Taxonomy
apiPackage: Api\Commerce\Taxonomy